"""add auth_used_reset_tokens table

Revision ID: 0c6a02896faa
Revises: 3f110f0242f1
Create Date: 2026-05-31 18:29:23.589963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6a02896faa'
down_revision: Union[str, None] = '3f110f0242f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_used_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_used_reset_tokens_token_hash'), 'auth_used_reset_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_used_reset_tokens_token_hash'), table_name='auth_used_reset_tokens')
    op.drop_table('auth_used_reset_tokens')
    # ### end Alembic commands ###
