"""add_file_uploads_table_and_transaction_receipt

Revision ID: 251a68462530
Revises: cdb07f6695e7
Create Date: 2026-05-30 22:59:36.648756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251a68462530'
down_revision: Union[str, None] = 'cdb07f6695e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('is_orphan', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_file_uploads_is_orphan', 'file_uploads', ['is_orphan'], unique=False)
    op.create_index('ix_file_uploads_user_id', 'file_uploads', ['user_id'], unique=False)
    op.add_column('cuan_transactions', sa.Column('receipt_file_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'cuan_transactions', 'file_uploads', ['receipt_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cuan_transactions', type_='foreignkey')
    op.drop_column('cuan_transactions', 'receipt_file_id')
    op.drop_index('ix_file_uploads_user_id', table_name='file_uploads')
    op.drop_index('ix_file_uploads_is_orphan', table_name='file_uploads')
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
