"""audit_fixes_add_indexes_nullable_constraints

Revision ID: 3f110f0242f1
Revises: 251a68462530
Create Date: 2026-05-31 14:13:45.643237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f110f0242f1'
down_revision: Union[str, None] = '251a68462530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blog_posts', 'excerpt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_blog_posts_published', 'blog_posts', ['published'], unique=False)
    op.create_index('ix_blog_posts_user_id', 'blog_posts', ['user_id'], unique=False)
    op.drop_constraint('blog_posts_user_id_fkey', 'blog_posts', type_='foreignkey')
    op.create_foreign_key(None, 'blog_posts', 'auth_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_chat_conversations_user_id', 'chat_conversations', ['user_id'], unique=False)
    op.create_index('ix_chat_tool_calls_message_id', 'chat_tool_calls', ['message_id'], unique=False)
    op.create_index('ix_cuan_accounts_user_id', 'cuan_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cuan_accounts_user_id', table_name='cuan_accounts')
    op.drop_index('ix_chat_tool_calls_message_id', table_name='chat_tool_calls')
    op.drop_index('ix_chat_conversations_user_id', table_name='chat_conversations')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.create_foreign_key('blog_posts_user_id_fkey', 'blog_posts', 'auth_users', ['user_id'], ['id'])
    op.drop_index('ix_blog_posts_user_id', table_name='blog_posts')
    op.drop_index('ix_blog_posts_published', table_name='blog_posts')
    op.alter_column('blog_posts', 'excerpt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('auth_users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
