"""Change transaction_date type to DateTime

Revision ID: 5fcd8645b9e8
Revises: 8d4f7c3a33ba
Create Date: 2025-07-12 17:20:29.584327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fcd8645b9e8'
down_revision: Union[str, None] = '8d4f7c3a33ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cuan_transactions', 'transaction_date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cuan_transactions', 'transaction_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
