"""add_content_blocks_to_chat_messages

Revision ID: a93ff4be88a7
Revises: a1b2c3d4e5f6
Create Date: 2026-05-27 20:53:09.613164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93ff4be88a7'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_conversations_user_id', table_name='chat_conversations')
    op.add_column('chat_messages', sa.Column('content_blocks', sa.JSON(), nullable=True))
    op.drop_index('ix_chat_messages_conversation_id', table_name='chat_messages')
    op.drop_index('ix_chat_tool_calls_message_id', table_name='chat_tool_calls')
    op.add_column('chat_user_settings', sa.Column('mcp_endpoints', sa.JSON(), nullable=True))
    op.drop_index('ix_chat_user_settings_user_id', table_name='chat_user_settings')
    op.drop_column('chat_user_settings', 'mcp_endpoint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_user_settings', sa.Column('mcp_endpoint', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_chat_user_settings_user_id', 'chat_user_settings', ['user_id'], unique=False)
    op.drop_column('chat_user_settings', 'mcp_endpoints')
    op.create_index('ix_chat_tool_calls_message_id', 'chat_tool_calls', ['message_id'], unique=False)
    op.create_index('ix_chat_messages_conversation_id', 'chat_messages', ['conversation_id'], unique=False)
    op.drop_column('chat_messages', 'content_blocks')
    op.create_index('ix_chat_conversations_user_id', 'chat_conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###
