"""add_indexes_for_query_performance

Revision ID: cdb07f6695e7
Revises: a93ff4be88a7
Create Date: 2026-05-30 20:06:26.847283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb07f6695e7'
down_revision: Union[str, None] = 'a93ff4be88a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_messages_conversation_created', 'chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_cuan_categories_user_name', 'cuan_categories', ['user_id', 'name'], unique=False)
    op.create_index('ix_cuan_categories_user_type', 'cuan_categories', ['user_id', 'type'], unique=False)
    op.create_index('ix_cuan_transactions_account_id', 'cuan_transactions', ['account_id'], unique=False)
    op.create_index('ix_cuan_transactions_dest_account_id', 'cuan_transactions', ['destination_account_id'], unique=False)
    op.create_index('ix_cuan_transactions_user_date', 'cuan_transactions', ['user_id', 'transaction_date'], unique=False)
    op.create_index('ix_cuan_transactions_user_type', 'cuan_transactions', ['user_id', 'transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cuan_transactions_user_type', table_name='cuan_transactions')
    op.drop_index('ix_cuan_transactions_user_date', table_name='cuan_transactions')
    op.drop_index('ix_cuan_transactions_dest_account_id', table_name='cuan_transactions')
    op.drop_index('ix_cuan_transactions_account_id', table_name='cuan_transactions')
    op.drop_index('ix_cuan_categories_user_type', table_name='cuan_categories')
    op.drop_index('ix_cuan_categories_user_name', table_name='cuan_categories')
    op.drop_index('ix_chat_messages_conversation_created', table_name='chat_messages')
    # ### end Alembic commands ###
