"""add account_number to cuan_accounts

Revision ID: dbcead8c70d2
Revises: 5fcd8645b9e8
Create Date: 2026-05-27 11:27:45.593120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbcead8c70d2'
down_revision: Union[str, None] = '5fcd8645b9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuan_accounts', sa.Column('account_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuan_accounts', 'account_number')
    # ### end Alembic commands ###
